### ISSUE TITLE
# Header

### ISSUE THREAD

**Issue by Natrosvili** [Natrosvili/Capstone-Project-movie-serien-app#1]
### Value Proposition

**As a User I need to have a header to be able to get access to every page of the Application

### Description

<img width="827" alt="Screenshot 2022-11-28 at 14 23 19" src="https://user-images.githubusercontent.com/100809251/204288429-e1e9a0b2-3d56-4fe5-9471-d65c4292b787.png">

### Acceptance Criteria

- [ ] general layout should fit mobile page sizes
- [ ] layout of header and navbar should comply with general mobile sizing

### Tasks

(for developers team)

- [ ] create the "Filmen", "Serien" & the buttons on the side of the header as Links. 
- [ ] Create the Seach Engine without the functionality, for now.
- [ ] use styled-components to style the header

### Sizing/Complexity

**S**
